= jdeprscan-gradle-plugin
:linkattrs:
:project-owner:   kordamp
:project-repo:    maven
:project-name:    jdeprscan-gradle-plugin
:project-group:   org.kordamp.gradle
:project-version: 0.9.0

image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]
image:https://img.shields.io/badge/donations-Patreon-orange.svg[link="https://www.patreon.com/user?u=6609318"]

---

Runs the `jdeprscan` command on the project's output.

== Usage

Option #1
[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
        gradlePluginPortal()
    }
    dependencies {
        classpath '{project-group}:{project-name}:{project-version}'
    }
}
apply plugin: '{project-group}.jdeprscan'
----

Option #2
[source,groovy]
[subs="attributes"]
----
plugins {
    id '{project-group}.jdeprscan' version '{project-version}'
}
----

This will add a `jdeprscanReport` task to your build, which will analyze the `main` sourceSets using the `runtime` configuration
as classpath.

== Configuration
=== Plugin configuration

The following properties can be specified in the `jdeprscanReport` task configuration

[options="header"]
|===
| Name           | Option                   | Property                 | Type         | Default Value
| forRemoval     | jdeprscan-for-removal    | jdeprscan.for.removal    | boolean      | false
| release        | jdeprscan-release        | jdeprscan.release        | int          | 9
| verbose        | jdeprscan-verbose        | jdeprscan.verbose        | boolean      | false
| javaHome       | jdeprscan-java-home      | jdeprscan.java.home      | String       |
| consoleOutput  | jdeprscan-console-output | jdeprscan.console.output | boolean      | true
| reportsDir     |                          |                          | File         | "${buildDir}/reports/jdeprscan"
| configurations | jdeprscan-configurations | jdeprscan.configurations | List<String> | ['runtime']
| sourceSets     | jdeprscan-sourcesets     | jdeprscan.sourcesets     | List<String> | ['main']
|===

Task properties may be defined on the command line using their option name, or their property name, such as

[source]
----
$ gradle jdeprscan --jdeprscan-verbose
$ gradle jdeprscan -Pjdeprscan.verbose=true
$ gradle jdeprscan -Djdeprscan.verbose=true
$ set JDEPRSCAN_VERBOSE=true
$ gradle jdeprscan
----

You may run this plugin in a build that relies Java 8 as long as you configure a valid path to a JDK9+ installation
directory using the `javaHome` property, for example

[source]
----
jdeprscanReport {
    javaHome = '/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home'
}
----

You may configure multiple sourceSets and configurations, which will be evaluated in a single report. The following snippet
shows how this plugin can be configured to run `jdeprscanReport` on production and test sources

[source]
----
jdeprscanReport {
    sourceSets = ['main', 'test']
    configurations = ['testRuntime']
}
----

