= jdeprscan-gradle-plugin
:linkattrs:
:project-name: jdeprscan-gradle-plugin
:plugin-version: 0.1.0

image:http://img.shields.io/travis/aalmiray/{project-name}/master.svg["Build Status", link="https://travis-ci.org/aalmiray/{project-name}"]
image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"]
image:https://api.bintray.com/packages/aalmiray/kordamp/{project-name}/images/download.svg[link="https://bintray.com/aalmiray/kordamp/{project-name}/_latestVersion"]
image:https://img.shields.io/badge/donations-Patreon-orange.svg[link="https://www.patreon.com/user?u=6609318"]

---

Runs the `jdeprscan` command on the project's output.

== Usage

Option #1
[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.kordamp.gradle:{project-name}:{plugin-version}
    }
}
apply plugin: 'org.kordamp.jdeprscan'
----

Option #2
[source,groovy]
[subs="attributes"]
----
plugins {
    id 'org.kordamp.jdeprscan' version '{plugin-version}'
}
----

This will add a `jdeprscan` task to your build, which will analyze the `main` sourceSets using the `runtime` configuration
as classpath.

== Configuration
=== Plugin configuration

The following properties can be specified in the `jdeprscan` task configuration

|===
| Name           | Type         | Default Value
| forRemoval     | boolean      | false
| release        | int          | 9
| verbose        | boolean      | false
| javaHome       | String       |
| consoleOutput  | boolean      | true
| reportsDir     | File         | "${buildDir}/reports/jdeprscan"
| configurations | List<String> | ['runtime']
| sourceSets     | List<String> | ['main']
|===

You may run this plugin in a build that relies Java 8 as long as you configure a valid path to a JDK9+ installation
directory using the `javaHome` property, for example

[source]
----
jdeprscan {
    javaHome = '/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home'
}
----

You may configure multiple sourceSets and configurations, which will be evaluated in a single report. The following snippet
shows how this plugin can be configured to run `jdeprscan` on production and test sources

[source]
----
jdeprscan {
    sourceSets = ['main', 'test']
    configurations = ['testRuntime']
}
----

