= jdeprscan-gradle-plugin
:linkattrs:
:project-owner:   kordamp
:project-repo:    maven
:project-name:    jdeprscan-gradle-plugin
:project-group:   org.kordamp.gradle
:project-version: 0.6.0

image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]
image:https://img.shields.io/badge/donations-Patreon-orange.svg[link="https://www.patreon.com/user?u=6609318"]

---

Runs the `jdeprscan` command on the project's output.

== Usage

Option #1
[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
        gradlePluginPortal()
    }
    dependencies {
        classpath '{project-group}:{project-name}:{project-version}'
    }
}
apply plugin: '{project-group}.jdeprscan'
----

Option #2
[source,groovy]
[subs="attributes"]
----
plugins {
    id '{project-group}.jdeprscan' version '{project-version}'
}
----

This will add a `jdeprscanReport` task to your build, which will analyze the `main` sourceSets using the `runtime` configuration
as classpath.

== Configuration
=== Plugin configuration

The following properties can be specified in the `jdeprscanReport` task configuration

|===
| Name           | Type         | Default Value
| forRemoval     | boolean      | false
| release        | int          | 9
| verbose        | boolean      | false
| javaHome       | String       |
| consoleOutput  | boolean      | true
| reportsDir     | File         | "${buildDir}/reports/jdeprscan"
| configurations | List<String> | ['runtime']
| sourceSets     | List<String> | ['main']
|===

You may run this plugin in a build that relies Java 8 as long as you configure a valid path to a JDK9+ installation
directory using the `javaHome` property, for example

[source]
----
jdeprscanReport {
    javaHome = '/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home'
}
----

You may configure multiple sourceSets and configurations, which will be evaluated in a single report. The following snippet
shows how this plugin can be configured to run `jdeprscanReport` on production and test sources

[source]
----
jdeprscanReport {
    sourceSets = ['main', 'test']
    configurations = ['testRuntime']
}
----

